- name: Install packages
  import_role:
    name: common

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files_to_copy }}"
  become: yes
  notify:
    - restart nginx

- name: Remove configuration files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_to_remove }}"
  become: yes
  notify:
    - restart nginx

- name: Enable sites
  file:
    src: "{{ nginx.config_path }}/sites-available/{{ item }}.conf"
    dest: "{{ nginx.config_path }}/sites-enabled/{{ item }}"
    state: link
  with_items: "{{ sites_to_enable }}"
  become: yes
  notify:
    - restart nginx
