dependencies:
  - git
  - tmux
  - zsh

files_to_copy:
  - .oh-my-zsh/custom/
  - .gitconfig
  - .tmux.conf
  - .zshrc

files_to_remove:
  - /etc/motd
  - "{{ ansible_user_dir }}/.bash_history"
  - "{{ ansible_user_dir }}/.bash_logout"
  - "{{ ansible_user_dir }}/.bashrc"
  - "{{ ansible_user_dir }}/.profile"
