- name: "CHIP Playbook"
  hosts: chip
  remote_user: chip
  become_method: sudo
  gather_facts: false

- import_playbook: system.yml
- import_playbook: user.yml
- import_playbook: nginx.yml
- import_playbook: postgresql.yml
- import_playbook: node.yml
- import_playbook: ruby.yml
