dependencies:
  - cron-apt
  - dosfstools
  - hfsplus
  - hfsprogs
  - hfsutils
  - nmap
  - rfkill

services:
  disabled:
    - avahi-daemon
    - avahi-daemon.socket
    - bluetooth
    - ModemManager
    - NetworkManager
    - NetworkManager-wait-online

sshd_config:
  - regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  - regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  - regexp: '^#?UsePAM'
    line: 'UsePAM no'
