sshd_config:
  - regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  - regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  - regexp: '^#?UsePAM'
    line: 'UsePAM no'

disabled_services:
  - avahi-daemon
  - avahi-daemon.socket
  - bluetooth
  - ModemManager
  - NetworkManager

dependencies:
  - cron-apt
  - dosfstools
  - hfsplus
  - hfsprogs
  - hfsutils
  - nmap
  - rfkill
