sshd_config:
  - regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  - regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  - regexp: '^#?UsePAM'
    line: 'UsePAM no'

dependencies:
  - cron-apt
  - dosfstools
  - hfsplus
  - hfsprogs
  - hfsutils
  - nmap
  - rfkill
  - tmux
