dependencies:
  - cron-apt
  - dosfstools
  - hfsplus
  - hfsprogs
  - hfsutils
  - nmap
  - rfkill

services_to_disable:
  - avahi-daemon
  - avahi-daemon.socket
  - bluetooth
  - ModemManager
  - NetworkManager
  - NetworkManager-wait-online

sshd_config:
  - regexp: '^#?(PasswordAuthentication)'
    line: '\1 no'
  - regexp: '^#?(PermitRootLogin)'
    line: '\1 no'
  - regexp: '^#?(PrintLastLog)'
    line: '\1 yes'
  - regexp: '^#?(PrintMotd)'
    line: '\1 yes'
  - regexp: '^#?(UsePAM)'
    line: '\1 no'
