dependencies:
  - bluetooth
  - cron-apt
  - hfsplus
  - hfsprogs
  - hfsutils
  - less
  - libpam-systemd
  - nmap
  - tmux

files_to_copy:
  - src: files/sshd_config
    dest: /etc/ssh/sshd_config

files_to_modify:
  - path: /etc/update-motd.d/10-uname
    mode: -x
  - path: /etc/update-motd.d/11-pine-a64-help-text
    mode: -x

files_to_remove:
  - /etc/motd
