- name: Get Netatalk binary path
  stat:
    path: /usr/local/sbin/netatalk
  register: netatalk__bin_path

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ netatalk__apt_packages }}"
  become: yes

- name: Download, configure, build, and install Netatalk {{ netatalk__version }}
  block:
    - unarchive:
        src: http://prdownloads.sourceforge.net/netatalk/netatalk-{{ netatalk__version }}.tar.bz2
        dest: "{{ ansible_env.HOME }}"
        remote_src: yes
    - command: ./configure --with-init-style=debian-systemd --without-libevent --without-tdb --with-cracklib --enable-krbV-uam --with-pam-confdir=/etc/pam.d --with-dbus-daemon=/usr/bin/dbus-daemon --with-dbus-sysconf-dir=/etc/dbus-1/system.d --with-tracker-pkgconfig-version=1.0
      args:
        chdir: "{{ netatalk__workspace }}"
    - command: make
      args:
        chdir: "{{ netatalk__workspace }}"
    - command: make install
      args:
        chdir: "{{ netatalk__workspace }}"
      become: yes
    - file:
        path: "{{ netatalk__workspace }}"
        state: absent
  when: not netatalk__bin_path.stat.exists

- name: Update {{ netatalk__nsswitch_config_path }} configuration
  lineinfile:
    path: "{{ netatalk__nsswitch_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ netatalk__nsswitch_config_lines }}"
  become: yes

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0664
  with_items: "{{ netatalk__config_files }}"
  become: yes

- name: Restart services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items: "{{ netatalk__services }}"
  become: yes
