- name: Install/update nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_path }}"
    version: "{{ nvm_version }}"
    clone: yes
    update: yes

- name: Install Node
  shell: |
    export NVM_DIR="{{ nvm_path }}"
    . {{ nvm_path }}/nvm.sh
    nvm install node
  register: node_installed
  changed_when: '"is already installed." not in node_installed.stderr'
