netatalk__apt_packages:
  - avahi-daemon
  - build-essential
  - libacl1-dev
  - libavahi-client-dev
  - libcrack2-dev
  - libdb-dev
  - libdbus-1-dev
  - libdbus-glib-1-dev
  - libevent-dev
  - libgcrypt-dev
  - libglib2.0-dev
  - libio-socket-inet6-perl
  - libkrb5-dev
  - libldap2-dev
  - libmariadbclient-dev
  - libpam0g-dev
  - libssl-dev
  - libtdb-dev
  - libtracker-miner-1.0-dev
  - libtracker-sparql-1.0-dev
  - libwrap0-dev
  - systemtap-sdt-dev
  - tracker

netatalk__config_files:
  - src: files/afpd.service
    dest: /etc/avahi/services/afpd.service
  - src: files/afp.conf
    dest: /usr/local/etc/afp.conf

netatalk__services:
  - avahi-daemon
  - netatalk

netatalk__version: 3.1.11

netatalk__workspace: "{{ ansible_env.HOME }}/netatalk-{{ netatalk__version }}"

netatalk__nsswitch_config_path: /etc/nsswitch.conf

netatalk__nsswitch_config_lines:
  - regexp: '^(hosts:.* dns)$'
    line: '\1 mdns4 mdns'
