- name: Install packages
  import_role:
    name: common

- name: Disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: "{{ services_to_disable }}"
  become: yes
  notify:
    - reboot

- name: Update SSH config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items: "{{ sshd_config }}"
  become: yes
  notify:
    - restart ssh
