- name: Install packages
  import_role:
    name: common

- name: Copy configuration files
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  with_items: "{{ files_to_copy }}"
  become: yes
  notify:
    - restart ssh

- name: Modify configuration files
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files_to_modify }}"
  become: yes

- name: Remove configuration files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_to_remove }}"
  become: yes
