- import_tasks: ../common/tasks/apt.yml
  vars:
    packages: "{{ shairport_sync__apt_packages }}"

- name: Clone alac repository
  git:
    repo: https://github.com/mikebrady/alac
    dest: "{{ shairport_sync__alac_workspace }}"
    version: "{{ shairport_sync__alac_version }}"
    accept_hostkey: yes

- block:
    - command: autoreconf -fi
      args:
        chdir: "{{ shairport_sync__alac_workspace }}"
    - name: Configure alac
      command: ./configure
      args:
        chdir: "{{ shairport_sync__alac_workspace }}"
    - name: Build alac
      make:
        chdir: "{{ shairport_sync__alac_workspace }}"
    - name: Install alac
      make:
        chdir: "{{ shairport_sync__alac_workspace }}"
        target: install
      become: yes
    - command: ldconfig
      args:
        chdir: "{{ shairport_sync__alac_workspace }}"
      become: yes

- name: Clone shairport-sync repository
  git:
    repo: https://github.com/mikebrady/shairport-sync
    dest: "{{ shairport_sync__workspace }}"
    version: "{{ shairport_sync__version }}"
    accept_hostkey: yes

- block:
    - command: autoreconf -fi
      args:
        chdir: "{{ shairport_sync__workspace }}"
    - name: Configure shairport-sync
      command: ./configure --sysconfdir=/etc --with-apple-alac --with-alsa --with-avahi --with-metadata --with-soxr --with-ssl=openssl --with-systemd
      args:
        chdir: "{{ shairport_sync__workspace }}"
    - name: Build shairport-sync
      make:
        chdir: "{{ shairport_sync__workspace }}"
    - name: Install shairport-sync
      make:
        chdir: "{{ shairport_sync__workspace }}"
        target: install
      become: yes

- name: Create configuration file
  template:
    src: shairport-sync.conf.j2
    dest: /etc/shairport-sync.conf
    owner: root
    group: root
    mode: 0664
  become: yes

- name: Enable and start shairport-sync service
  systemd:
    name: shairport-sync
    state: started
    enabled: yes
  become: yes
