- name: Install packages
  import_role:
    name: common

- name: Disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: "{{ disabled_services }}"
  become: yes
  notify:
    - reboot

- name: Disable WiFi power management
  get_url:
    url: http://fordsfords.github.io/wlan_pwr/wlan_pwr
    dest: /etc/network/if-up.d/wlan-power-save
    mode: +x
  become: yes
  notify:
    - reboot

- name: Update SSH config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items: "{{ sshd_config }}"
  become: yes
  notify:
    - restart ssh
