shairport_sync__apt_packages:
  - autoconf
  - automake
  - avahi-daemon
  - build-essential
  - git
  - libasound2-dev
  - libavahi-client-dev
  - libconfig-dev
  - libpopt-dev
  - libsoxr-dev
  - libssl-dev
  - libtool
  - xmltoman

shairport_sync__workspace: "{{ ansible_env.HOME }}/workspace/shairport-sync"

shairport_sync__alac_workspace: "{{ ansible_env.HOME }}/workspace/alac"
