- name: Install packages
  import_role:
    name: common

- name: Enable user lingering
  command: loginctl enable-linger {{ user }}
  become: yes

- name: Change shell to ZSH
  command: chsh {{ user }} -s /bin/zsh
  become: yes

- name: Install oh-my-zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    exit 0
  register: oh_my_zsh_installed
  changed_when: '"You already have Oh My Zsh installed." not in oh_my_zsh_installed.stdout'

- name: Copy user configuration files
  copy:
    src: files/home/{{ item }}
    dest: $HOME/{{ item }}
  with_items:
    - .oh-my-zsh/custom/
    - .gemrc
    - .gitconfig
    - .npmrc
    - .zshrc

- name: Remove Bash files
  file:
    path: $HOME/{{ item }}
    state: absent
  with_items:
    - .bash_history
    - .bash_logout
    - .bashrc
    - .profile
