- name: "Pine64 Playbook"
  hosts: pine64
  remote_user: pine64
  become_method: sudo
  gather_facts: false

- import_playbook: system.yml
- import_playbook: user.yml
- import_playbook: node.yml
- import_playbook: ruby.yml
