- name: Install locales package
  apt:
    name: locales
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: Set locale in /etc/locale.gen
  lineinfile:
    path: /etc/locale.gen
    regexp: '^# ({{ locale }} UTF-8)$'
    line: '\1'
    backrefs: yes

- name: Set locale in /etc/default/locale
  lineinfile:
    path: /etc/default/locale
    regexp: '^(LANG="{{ locale }}")'
    line: '\1'
    backrefs: yes

- name: Reconfigure locales
  command: dpkg-reconfigure -f noninteractive locales
