- name: Install packages
  import_role:
    name: common

- name: Update dnsmasq config
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    backrefs: yes
  with_items: "{{ dnsmasq_config }}"
  become: yes
  notify:
    - restart dnsmasq

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files_to_copy }}"
  become: yes
  notify:
    - restart dnsmasq
