- name: Install packages
  import_role:
    name: common

- name: Copy configuration files
  copy:
    src: files/{{ item }}
    dest: "{{ nginx.config_dir }}/{{ item }}"
  with_items: "{{ files_to_copy }}"
  become: yes
  notify:
    - restart nginx
